version: '3.8'

services:
    kafka:
      image: 681941410274.dkr.ecr.eu-west-1.amazonaws.com/mirror/confluentinc/cp-kafka:7.4.1
      container_name: kafka
      ports:
        - '9092:9092'
      expose:
        - '29092'
      healthcheck:
        test: nc -z localhost 9092 || exit -1
        start_period: 5s
        interval: 5s
        timeout: 10s
        retries: 10
      restart: on-failure
      environment:
        KAFKA_ENABLE_KRAFT: 'yes'
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_BROKER_ID: '1'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
        ALLOW_PLAINTEXT_LISTENER: 'yes'
        KAFKA_NODE_ID: '1'
        CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
        KAFKA_LOG_FLUSH_INTERVAL_MS: '100'
        KAFKA_LOG4J_ROOT_LOGLEVEL: 'INFO'
        KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 100
        KAFKA_MIN_INSYNC_REPLICAS: '1'
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
